### ISSUE TITLE
Youtube Network List

### ISSUE THREAD

**Issue by Lunatixz** [PseudoTV/PseudoTV_Lists#1]
@PseudoTV/collaborators 

Can you guys start building up the Youtube network list? 
Would be cool if we can get channels from TV networks, ie. A&E, ABC, NBC

Start pooling together all related sources to create channels... Thanks

https://github.com/PseudoTV/PseudoTV_Lists/blob/master/youtube_channels_networks.ini

**Comment by RayW1986** [comment]
I could start collecting the official YouTube channels of the UK networks. Do you ideally want them having full episodes or are channels with mostly clips acceptable?

---- Lunatixz wrote ----

@PseudoTV/collaborators

Can you guys start building up the Youtube network list?
Would be cool if we can get channels from TV networks, ie. A&E, ABC, NBC

Start pooling together all related sources to create channels... Thanks

---

Reply to this email directly or view it on GitHub:
https://github.com/PseudoTV/PseudoTV_Lists/issues/1

**Comment by Lunatixz** [comment]
full content is a plus... I want to stay away from to many clips. Clips are okay for news networks, but most ppl want content that is more than a few minutes.

Thanks

**Comment by toyap** [comment]
I can start on US/Canada networks this weekend between homework.

**Comment by Lunatixz** [comment]
Great, Thanks

**Comment by Lunatixz** [comment]
@PseudoTV/collaborators any luck with the network lists?
